export interface LocationPage {
  location: string;
  state: string;
  slug: string;
  metaTitle: string;
  metaDescription: string;
  h1: string;
  heroSubtitle: string;
  introParagraph: string;
  neighborhoods: string[];
  localFAQ_question: string;
  localFAQ_answer: string;
  reviewQuote: string;
  reviewAuthor: string;
  zoneCopy: string;
  finalHeadline: string;
  finalSub: string;
  bilingualFlag: boolean;
  pageType: "nyc" | "nj";
}

export const locationPages: Record<string, LocationPage> = {
  "laundry-pickup-alphabet-city": {
    location: "Alphabet City",
    state: "NYC",
    slug: "laundry-pickup-alphabet-city",
    metaTitle: "Laundry Pickup & Delivery in Alphabet City, NYC | We Deliver Laundry",
    metaDescription: "On-demand laundry pickup and delivery in Alphabet City, NYC. Wash, dry & fold returned in 24 hours. Starting at $1.95/lb. Free pickup. Schedule online.",
    h1: "Alphabet City Doesn't Have Time for Laundry.",
    heroSubtitle: "Between the art openings, late nights, and everything in between — nobody on Avenue C is spending Sunday at a laundromat. We pick up, wash everything with care, and deliver back perfectly folded within 24 hours.",
    introParagraph: "If you live on Avenue A, B, C, or D, you already know the deal: your building doesn't have in-unit laundry, the local laundromats are packed on weekends, and Sunday mornings are too good to waste on a spin cycle. We Deliver Laundry picks up from your door, washes everything with gentle detergents, and has it back at your building the next day. Starting at $1.95/lb on the weekly plan.",
    neighborhoods: ["East Village", "Lower East Side", "NoHo", "Nolita", "Chelsea"],
    localFAQ_question: "Do you pick up from apartment buildings on Avenue A, B, C, and D?",
    localFAQ_answer: "Yes — we pick up from all buildings throughout Alphabet City including Avenue A through D. Schedule your pickup online and we'll come to your door. No minimums, no harsh chemicals, 24-hour turnaround.",
    reviewQuote: "I've lived on Avenue C for three years and always dreaded laundry day. WDL changed that completely. Pickup at my door, back the next day — done.",
    reviewAuthor: "Sofia M., Alphabet City",
    zoneCopy: "We pick up from your building on Avenue A, B, C, or D. Schedule before midnight, we're there the next morning. Same 24-hour turnaround, no minimums.",
    finalHeadline: "Stop Doing Laundry.",
    finalSub: "Seriously. Schedule your first Alphabet City pickup and get your time back. Avenue C will still be there — your laundry pile won't.",
    bilingualFlag: false,
    pageType: "nyc",
  },
  "laundry-pickup-battery-park-city": {
    location: "Battery Park City",
    state: "NYC",
    slug: "laundry-pickup-battery-park-city",
    metaTitle: "Laundry Pickup & Delivery in Battery Park City, NYC | We Deliver Laundry",
    metaDescription: "Laundry pickup and delivery in Battery Park City, NYC. Wash, dry & fold returned to your door in 24 hours. Starting at $1.95/lb. Free pickup. Book today.",
    h1: "Battery Park City. Hudson Views. Zero Laundry.",
    heroSubtitle: "You've got the river views. We've got the laundry. Free pickup from your building, professionally washed and folded without harsh chemicals, back at your door in 24 hours.",
    introParagraph: "Battery Park City residents have some of the best views in New York — and the last thing you should be doing is hauling laundry bags to a laundromat. We Deliver Laundry picks up from North End Avenue, River Terrace, the Esplanade buildings, and everywhere in between. Everything washed with gentle detergents, perfectly folded, back in 24 hours. Weekly plan starts at $1.95/lb.",
    neighborhoods: ["Financial District", "Tribeca", "SoHo", "Lower East Side", "Civic Center"],
    localFAQ_question: "Do you pick up from the residential buildings in Battery Park City?",
    localFAQ_answer: "Yes — we serve all residential addresses in Battery Park City including North End Avenue, River Terrace, and the Esplanade buildings. Free pickup, 24-hour turnaround, no minimums.",
    reviewQuote: "I work long hours in FiDi and the last thing I want on weekends is laundry. WDL picks up Friday and it's back Saturday. My weekends are mine again.",
    reviewAuthor: "Daniel R., Battery Park City",
    zoneCopy: "Picking up from North End Avenue, River Terrace, the Esplanade buildings, and all Battery Park City addresses. 24-hour turnaround guaranteed.",
    finalHeadline: "Weekends Are for the View.",
    finalSub: "Not for laundry. Schedule your first Battery Park City pickup and keep your weekends exactly the way they should be.",
    bilingualFlag: false,
    pageType: "nyc",
  },
  "laundry-pickup-bowery": {
    location: "Bowery",
    state: "NYC",
    slug: "laundry-pickup-bowery",
    metaTitle: "Laundry Pickup & Delivery on the Bowery, NYC | We Deliver Laundry",
    metaDescription: "Laundry pickup and delivery on the Bowery, NYC. Wash, dry & fold returned in 24 hours. Starting at $1.95/lb. Free pickup from your building. Schedule today.",
    h1: "Bowery Living. Zero Laundry Days.",
    heroSubtitle: "We pick up from your building on the Bowery, wash and fold everything without harsh chemicals, and have it back at your door in 24 hours.",
    introParagraph: "The Bowery has come a long way — but lugging laundry bags down the stairs hasn't gotten any easier. We Deliver Laundry picks up from your building on the Bowery corridor, washes everything carefully, and delivers it back the next day perfectly folded. No laundromat lines, no quarters, no Sunday wasted. Starting at $1.95/lb on the weekly plan.",
    neighborhoods: ["NoHo", "Nolita", "Lower East Side", "Chinatown", "East Village"],
    localFAQ_question: "Do you serve buildings on the Bowery between SoHo and the Lower East Side?",
    localFAQ_answer: "Yes — we pick up from all buildings along the Bowery corridor. NoHo, Nolita, and the Lower East Side are also covered. Free pickup, 24-hour turnaround.",
    reviewQuote: "I've lived on the Bowery for three years and lugging laundry was always the worst part of the week. WDL changed that completely. Pickup Monday, back Tuesday, done.",
    reviewAuthor: "Marcus T., Bowery",
    zoneCopy: "Picking up from all buildings on the Bowery corridor. NoHo, Nolita, and the Lower East Side also covered. 24-hour turnaround every time.",
    finalHeadline: "The Bowery Has Better Things.",
    finalSub: "Schedule your first pickup and cross laundry off your list permanently.",
    bilingualFlag: false,
    pageType: "nyc",
  },
  "laundry-pickup-carnegie-hill": {
    location: "Carnegie Hill",
    state: "NYC",
    slug: "laundry-pickup-carnegie-hill",
    metaTitle: "Laundry Pickup & Delivery in Carnegie Hill, NYC | We Deliver Laundry",
    metaDescription: "Premium laundry pickup and delivery in Carnegie Hill, NYC. Wash, dry & fold returned to your door in 24 hours. Starting at $1.95/lb. Free pickup. Schedule today.",
    h1: "Carnegie Hill. Premium Service. Zero Effort.",
    heroSubtitle: "Free pickup from your Upper East Side building. Professionally washed, dried, and folded without harsh chemicals. Back at your door in 24 hours — no laundromat required.",
    introParagraph: "Carnegie Hill sets a high bar for everything — and your laundry service should be no exception. We Deliver Laundry picks up from your building, washes every item without harsh chemicals, and delivers it back perfectly folded the next day. Families, professionals, and anyone who values their time on the UES trusts us with their weekly laundry. Starting at $1.95/lb on the weekly plan.",
    neighborhoods: ["Lenox Hill", "Yorkville", "Upper East Side", "East Harlem"],
    localFAQ_question: "Do you pick up from Carnegie Hill buildings on the Upper East Side?",
    localFAQ_answer: "Yes — we serve all Carnegie Hill addresses. Lenox Hill and Yorkville are also covered. Free pickup from your building, 24-hour turnaround, no minimums.",
    reviewQuote: "We're a family of four in Carnegie Hill and laundry was consuming our entire Sunday. WDL picks up weekly and everything comes back perfectly folded. Worth every penny.",
    reviewAuthor: "Claire B., Carnegie Hill",
    zoneCopy: "Pickup from all Carnegie Hill buildings and the surrounding UES streets. Lenox Hill, Yorkville, and the Upper East Side also covered.",
    finalHeadline: "Your Sunday Belongs to You.",
    finalSub: "Schedule your first Carnegie Hill pickup and reclaim your weekend. Clean clothes, zero effort, next-day delivery.",
    bilingualFlag: false,
    pageType: "nyc",
  },
  "laundry-pickup-central-harlem": {
    location: "Central Harlem",
    state: "NYC",
    slug: "laundry-pickup-central-harlem",
    metaTitle: "Laundry Pickup & Delivery in Central Harlem, NYC | We Deliver Laundry",
    metaDescription: "Laundry pickup and delivery in Central Harlem, NYC. Wash, dry & fold returned in 24 hours. Starting at $1.95/lb. Free pickup from your building. Book today.",
    h1: "Harlem, Meet Your New Laundry Service.",
    heroSubtitle: "Free pickup from your building in Central Harlem. Everything washed, dried, and folded. Delivered back within 24 hours — no laundromat, no hassle.",
    introParagraph: "Central Harlem is one of New York's most vibrant neighborhoods — and its residents are some of the busiest people in the city. We Deliver Laundry picks up from your door between 110th and 145th Street, washes everything with gentle detergents, and delivers it back the next day perfectly folded. No more Sunday laundromat runs. Starting at $1.95/lb on the weekly plan.",
    neighborhoods: ["Hamilton Heights", "Sugar Hill", "Morningside Heights", "East Harlem", "Washington Heights"],
    localFAQ_question: "Do you pick up from buildings in Central Harlem between 110th and 145th Street?",
    localFAQ_answer: "Yes — we serve all of Central Harlem from 110th to 145th Street. Hamilton Heights, Sugar Hill, and Morningside Heights are also covered. Free pickup, 24-hour turnaround.",
    reviewQuote: "I work two jobs and laundry was always the thing that fell through the cracks. WDL picks up Tuesday and everything is back Wednesday. Finally got my evenings back.",
    reviewAuthor: "Darius M., Central Harlem",
    zoneCopy: "Pickup from 110th to 145th Street and all surrounding blocks. Hamilton Heights, Morningside Heights, and Sugar Hill also covered.",
    finalHeadline: "Your Time Is Too Valuable.",
    finalSub: "Schedule your first Harlem pickup and get your evenings back. Next-day delivery, no laundromat required.",
    bilingualFlag: false,
    pageType: "nyc",
  },
  "laundry-pickup-chelsea": {
    location: "Chelsea",
    state: "NYC",
    slug: "laundry-pickup-chelsea",
    metaTitle: "Laundry Pickup & Delivery in Chelsea, NYC | We Deliver Laundry",
    metaDescription: "Laundry pickup and delivery in Chelsea, NYC. Wash, dry & fold returned to your door in 24 hours. Starting at $1.95/lb. Free pickup. Book your first pickup today.",
    h1: "Chelsea. Your Laundry Is Handled.",
    heroSubtitle: "Free pickup from your Chelsea building between 8th and 10th Avenue. Washed, dried, and folded without harsh chemicals. Back at your door in 24 hours.",
    introParagraph: "Chelsea is packed with galleries, restaurants, and things worth doing — none of which involve a laundromat. We Deliver Laundry picks up from your building between 14th and 30th Street, washes everything with care, and delivers it back perfectly folded the next day. Free pickup, no harsh chemicals, starting at $1.95/lb on the weekly plan.",
    neighborhoods: ["Hell's Kitchen", "West Village", "Flatiron", "Gramercy Park", "Meatpacking District"],
    localFAQ_question: "Do you serve buildings in Chelsea between 14th and 30th Street?",
    localFAQ_answer: "Yes — we pick up from all Chelsea addresses. Hell's Kitchen, West Village, and Flatiron are also covered. Free pickup, 24-hour turnaround, no minimums.",
    reviewQuote: "Between work and everything else happening in Chelsea, laundry was always last on the list. WDL makes it completely painless. Pickup at my door, back the next day.",
    reviewAuthor: "Priya K., Chelsea",
    zoneCopy: "Pickup from all Chelsea addresses between 14th and 30th Street. Hell's Kitchen, West Village, and Flatiron also covered.",
    finalHeadline: "Chelsea Doesn't Stop for Laundry.",
    finalSub: "Neither should you. Schedule your first pickup and keep moving.",
    bilingualFlag: false,
    pageType: "nyc",
  },
  "laundry-pickup-chinatown": {
    location: "Chinatown",
    state: "NYC",
    slug: "laundry-pickup-chinatown",
    metaTitle: "Laundry Pickup & Delivery in Chinatown, NYC | We Deliver Laundry",
    metaDescription: "Laundry pickup and delivery in Chinatown, NYC. Wash, dry & fold returned in 24 hours. Starting at $1.95/lb. Free pickup from your door. Schedule online today.",
    h1: "Chinatown's On-Demand Laundry Service.",
    heroSubtitle: "We pick up from your building in Chinatown, wash and fold everything without harsh chemicals, and deliver back within 24 hours. No more laundromat lines.",
    introParagraph: "Chinatown is one of New York's most densely populated neighborhoods — which means laundromat lines are long and machines are always full. We Deliver Laundry picks up from your door, washes everything with gentle detergents, and delivers it back the next day. No waiting, no quarters, no carrying bags. Starting at $1.95/lb on the weekly plan.",
    neighborhoods: ["Little Italy", "Lower East Side", "Two Bridges", "Civic Center", "NoLiTa"],
    localFAQ_question: "Do you pick up from apartments in Chinatown?",
    localFAQ_answer: "Yes — we serve all Chinatown addresses. Little Italy, Lower East Side, and Two Bridges are also covered. Free pickup from your door, 24-hour turnaround.",
    reviewQuote: "My building in Chinatown doesn't have in-unit laundry and the local laundromats are always packed. WDL picks up from my door and brings it back the next day.",
    reviewAuthor: "Mei L., Chinatown",
    zoneCopy: "Pickup from all Chinatown addresses. Little Italy, Lower East Side, and Two Bridges also covered. Same-day pickup available.",
    finalHeadline: "No More Laundromat Lines.",
    finalSub: "Schedule your first Chinatown pickup. Pickup from your door, back tomorrow, perfectly folded.",
    bilingualFlag: false,
    pageType: "nyc",
  },
  "laundry-pickup-east-harlem": {
    location: "East Harlem",
    state: "NYC",
    slug: "laundry-pickup-east-harlem",
    metaTitle: "Laundry Pickup & Delivery in East Harlem, NYC | We Deliver Laundry",
    metaDescription: "Laundry pickup and delivery in East Harlem (El Barrio), NYC. Wash, dry & fold returned in 24 hours. Starting at $1.95/lb. Free pickup. Servicio en español disponible.",
    h1: "East Harlem. Tu Ropa Limpia en 24 Horas.",
    heroSubtitle: "Free pickup from your building in East Harlem. Washed, dried, and folded — back at your door in 24 hours. Servicio disponible en español.",
    introParagraph: "El Barrio es una comunidad llena de energía, cultura e historia — y tu tiempo vale demasiado para pasarlo en una lavandería. We Deliver Laundry recoge en tu puerta, lava todo con cuidado sin productos agresivos, y te lo devuelve perfectamente doblado al día siguiente. Desde $1.95/lb con el plan semanal. Servicio disponible en inglés y español.",
    neighborhoods: ["Central Harlem", "Lenox Hill", "Upper East Side", "Yorkville"],
    localFAQ_question: "¿Recogen ropa en East Harlem / El Barrio?",
    localFAQ_answer: "Sí — recogemos en todas las direcciones de East Harlem, desde la calle 96 hasta la 125. Servicio disponible en español. Recogida gratis, entrega en 24 horas.",
    reviewQuote: "Llevo años viviendo en El Barrio y la lavandería siempre era un dolor de cabeza. WDL recoge en mi puerta y lo trae de vuelta al día siguiente. Increíble servicio.",
    reviewAuthor: "Rosa M., East Harlem / El Barrio",
    zoneCopy: "Pickup from 96th to 125th Street, east of Fifth Avenue. Bilingual service available. Spanish Harlem and surrounding blocks fully covered.",
    finalHeadline: "El Barrio No Tiene Tiempo Que Perder.",
    finalSub: "Schedule your first pickup. Bilingual service available. Pickup today, back tomorrow.",
    bilingualFlag: true,
    pageType: "nyc",
  },
  "laundry-pickup-east-village": {
    location: "East Village",
    state: "NYC",
    slug: "laundry-pickup-east-village",
    metaTitle: "Laundry Pickup & Delivery in the East Village, NYC | We Deliver Laundry",
    metaDescription: "Laundry pickup and delivery in the East Village, NYC. Wash, dry & fold returned in 24 hours. Starting at $1.95/lb. Free pickup from your building. Book today.",
    h1: "East Village — We Handle Laundry, You Handle Everything Else.",
    heroSubtitle: "Free pickup from your East Village building. Washed, dried, and folded without harsh chemicals. Back at your door in 24 hours — while you do literally anything else.",
    introParagraph: "East Village apartments are famously small and the neighborhood is famously busy. Spending two hours at a laundromat on Sunday is a waste of your time and your neighborhood. We Deliver Laundry picks up from your building between 1st and 14th Street, washes everything with gentle detergents, and delivers it back the next morning perfectly folded. Starting at $1.95/lb on the weekly plan.",
    neighborhoods: ["Alphabet City", "Lower East Side", "NoHo", "Nolita", "Gramercy Park"],
    localFAQ_question: "Do you serve apartments in the East Village between 1st and 14th Street?",
    localFAQ_answer: "Yes — we pick up from all East Village buildings east of Third Avenue. Alphabet City, Lower East Side, and NoHo are also covered. Free pickup, 24-hour turnaround.",
    reviewQuote: "East Village apartments are small and busy. I was spending two hours every Sunday at the laundromat. Now I schedule Monday morning and it's back Tuesday. That Sunday is mine.",
    reviewAuthor: "Jamie R., East Village",
    zoneCopy: "Pickup from all buildings between 1st and 14th Street, east of Third Avenue. Alphabet City, Lower East Side, and NoHo also covered.",
    finalHeadline: "The East Village Never Sleeps.",
    finalSub: "Neither does your laundry. Let us handle it. Schedule your first pickup — back tomorrow, perfectly folded.",
    bilingualFlag: false,
    pageType: "nyc",
  },
  "laundry-pickup-financial-district": {
    location: "Financial District",
    state: "NYC",
    slug: "laundry-pickup-financial-district",
    metaTitle: "Laundry Pickup & Delivery in the Financial District, NYC | We Deliver Laundry",
    metaDescription: "Laundry pickup and delivery in the Financial District (FiDi), NYC. Wash, dry & fold returned in 24 hours. Starting at $1.95/lb. Free pickup. Schedule online today.",
    h1: "FiDi Residents — Your Time Is Worth More Than Laundry.",
    heroSubtitle: "Free pickup from your Financial District building. Professionally washed, dried, and folded. Back at your door in 24 hours — weekly plan starts at $1.95/lb.",
    introParagraph: "You track dollars for a living. Every hour matters. Spending your Saturday at a laundromat is the worst possible ROI on your time. We Deliver Laundry picks up from your FiDi building, handles everything professionally, and delivers it back the next day. No harsh chemicals, no commitment, just clean clothes. Starting at $1.95/lb on the weekly plan.",
    neighborhoods: ["Battery Park City", "Tribeca", "Civic Center", "Lower East Side", "South Street Seaport"],
    localFAQ_question: "Do you pick up from residential buildings in the Financial District?",
    localFAQ_answer: "Yes — we serve all FiDi residential buildings. Battery Park City, Tribeca, and Civic Center are also covered. Free pickup, 24-hour turnaround.",
    reviewQuote: "Working in finance and living in FiDi means zero free time. WDL completely removed laundry from my weekend. Weekly pickup, always on time, always perfect. Worth every dollar.",
    reviewAuthor: "Alex C., Financial District",
    zoneCopy: "Pickup from all FiDi residential buildings. Battery Park City, Tribeca, and Civic Center also covered.",
    finalHeadline: "Your Weekend Is Too Valuable.",
    finalSub: "Don't spend it on laundry. Schedule your first FiDi pickup and get it back.",
    bilingualFlag: false,
    pageType: "nyc",
  },
  "laundry-pickup-flatiron": {
    location: "Flatiron District",
    state: "NYC",
    slug: "laundry-pickup-flatiron",
    metaTitle: "Laundry Pickup & Delivery in the Flatiron District, NYC | We Deliver Laundry",
    metaDescription: "Laundry pickup and delivery in the Flatiron District, NYC. Wash, dry & fold returned in 24 hours. Starting at $1.95/lb. Free pickup from your building. Book today.",
    h1: "Flatiron — Sharp Building, Sharper Service.",
    heroSubtitle: "Free pickup from your Flatiron building. Washed, folded, and back at your door the next day. No laundromat, no hassle.",
    introParagraph: "The Flatiron District sits at the intersection of everything — and the people who live here move fast. We Deliver Laundry picks up from your building, washes everything without harsh chemicals, and delivers it back the next day perfectly folded. The weekly plan keeps your laundry on autopilot. Starting at $1.95/lb.",
    neighborhoods: ["Chelsea", "Gramercy Park", "Midtown", "Union Square", "Murray Hill"],
    localFAQ_question: "Do you serve apartments in the Flatiron District?",
    localFAQ_answer: "Yes — we pick up from all Flatiron addresses. Chelsea, Gramercy Park, and Union Square are also covered. Free pickup, 24-hour turnaround.",
    reviewQuote: "Living in Flatiron and working nearby, I never had time to deal with laundry. WDL's weekly plan is perfect — same pickup time every week and everything comes back perfect.",
    reviewAuthor: "Sarah M., Flatiron",
    zoneCopy: "Pickup from all Flatiron addresses. Chelsea, Gramercy Park, Union Square, and Midtown South also covered.",
    finalHeadline: "Flatiron Never Slows Down.",
    finalSub: "Neither should you. Schedule your first pickup and check laundry off your list for good.",
    bilingualFlag: false,
    pageType: "nyc",
  },
  "laundry-pickup-gramercy-park": {
    location: "Gramercy Park",
    state: "NYC",
    slug: "laundry-pickup-gramercy-park",
    metaTitle: "Laundry Pickup & Delivery in Gramercy Park, NYC | We Deliver Laundry",
    metaDescription: "Laundry pickup and delivery in Gramercy Park, NYC. Wash, dry & fold returned to your door in 24 hours. Starting at $1.95/lb. Free pickup. Schedule online today.",
    h1: "Gramercy Park. Refined Living, Zero Laundry Days.",
    heroSubtitle: "Free pickup from your Gramercy building. Professionally washed without harsh chemicals, perfectly folded, back at your door in 24 hours.",
    introParagraph: "Gramercy Park is one of Manhattan's most distinctive neighborhoods — and the standard here is high. We Deliver Laundry matches that standard with consistent, reliable pickup from your building, professional washing without harsh chemicals, and perfect folding every time. The weekly plan keeps your wardrobe fresh without lifting a finger. Starting at $1.95/lb.",
    neighborhoods: ["Flatiron", "Murray Hill", "Kips Bay", "Stuyvesant Town", "East Village"],
    localFAQ_question: "Do you pick up from buildings near Gramercy Park?",
    localFAQ_answer: "Yes — we serve all Gramercy Park buildings. Flatiron, Murray Hill, and Kips Bay are also covered. Free pickup, 24-hour turnaround.",
    reviewQuote: "Gramercy is a neighborhood that values quality and WDL delivers exactly that. Consistent, on-time, and my clothes come back better folded than I ever managed myself.",
    reviewAuthor: "Katherine W., Gramercy Park",
    zoneCopy: "Pickup from all Gramercy Park buildings. Flatiron, Murray Hill, Kips Bay, and Stuyvesant Town also covered.",
    finalHeadline: "The Park Is for Relaxing.",
    finalSub: "Not for thinking about laundry. Schedule your first Gramercy pickup and keep it that way.",
    bilingualFlag: false,
    pageType: "nyc",
  },
  "laundry-pickup-greenwich-village": {
    location: "Greenwich Village",
    state: "NYC",
    slug: "laundry-pickup-greenwich-village",
    metaTitle: "Laundry Pickup & Delivery in Greenwich Village, NYC | We Deliver Laundry",
    metaDescription: "Laundry pickup and delivery in Greenwich Village, NYC. Wash, dry & fold returned in 24 hours. Starting at $1.95/lb. Free pickup from your building. Book today.",
    h1: "The Village. No Time for Laundromats.",
    heroSubtitle: "Free pickup from your Greenwich Village building. Washed, dried, and folded without harsh chemicals. Back at your door in 24 hours.",
    introParagraph: "Greenwich Village has better restaurants, better parks, and better things to do than a laundromat. We Deliver Laundry picks up from your building, washes everything with gentle detergents, and delivers it back the next day perfectly folded. More time for the things that make this neighborhood worth living in. Starting at $1.95/lb on the weekly plan.",
    neighborhoods: ["West Village", "NoHo", "SoHo", "Chelsea", "Tribeca", "Meatpacking District"],
    localFAQ_question: "Do you serve apartments in Greenwich Village?",
    localFAQ_answer: "Yes — we pick up from all Greenwich Village addresses. West Village, NoHo, SoHo, and Chelsea are also covered. Free pickup, 24-hour turnaround.",
    reviewQuote: "Between the restaurants, the parks, and everything Greenwich Village has going on, spending Sunday at a laundromat felt like a crime. WDL fixed that completely.",
    reviewAuthor: "Olivia P., Greenwich Village",
    zoneCopy: "Pickup from all Greenwich Village addresses. West Village, NoHo, SoHo, and Chelsea also covered.",
    finalHeadline: "The Village Has Better Plans.",
    finalSub: "Schedule your first pickup and stop wasting your weekends at the laundromat.",
    bilingualFlag: false,
    pageType: "nyc",
  },
  "laundry-pickup-hamilton-heights": {
    location: "Hamilton Heights",
    state: "NYC",
    slug: "laundry-pickup-hamilton-heights",
    metaTitle: "Laundry Pickup & Delivery in Hamilton Heights, NYC | We Deliver Laundry",
    metaDescription: "Laundry pickup and delivery in Hamilton Heights, NYC. Wash, dry & fold returned in 24 hours. Starting at $1.95/lb. Free pickup from your building. Schedule today.",
    h1: "Hamilton Heights. Big Week. Clean Clothes.",
    heroSubtitle: "Free pickup from your Hamilton Heights building. Washed, folded, and back in 24 hours. No laundromat run required.",
    introParagraph: "Hamilton Heights is one of Upper Manhattan's most sought-after neighborhoods — and its residents don't have time to waste on laundry. We Deliver Laundry picks up from your door, handles everything with care, and delivers it back the next day perfectly folded. Washington Heights, Sugar Hill, and Harlem are also covered. Starting at $1.95/lb on the weekly plan.",
    neighborhoods: ["Sugar Hill", "Washington Heights", "Central Harlem", "Morningside Heights"],
    localFAQ_question: "Do you pick up from Hamilton Heights buildings in Upper Manhattan?",
    localFAQ_answer: "Yes — we serve all Hamilton Heights addresses. Washington Heights, Sugar Hill, and Harlem are also covered. Free pickup, 24-hour turnaround.",
    reviewQuote: "Hamilton Heights is a neighborhood on the rise and WDL fits right in. Reliable pickup, fast turnaround, and my clothes always come back perfectly folded.",
    reviewAuthor: "Marcus J., Hamilton Heights",
    zoneCopy: "Pickup from all Hamilton Heights addresses. Washington Heights, Sugar Hill, Harlem, and Morningside Heights also covered.",
    finalHeadline: "Upper Manhattan Doesn't Slow Down.",
    finalSub: "Neither does WDL. Schedule your first Hamilton Heights pickup today.",
    bilingualFlag: false,
    pageType: "nyc",
  },
  "laundry-pickup-harlem": {
    location: "Harlem",
    state: "NYC",
    slug: "laundry-pickup-harlem",
    metaTitle: "Laundry Pickup & Delivery in Harlem, NYC | We Deliver Laundry",
    metaDescription: "Laundry pickup and delivery in Harlem, NYC. Wash, dry & fold returned in 24 hours. Starting at $1.95/lb. Free pickup from your building. Schedule online today.",
    h1: "Harlem, Meet Your New Favorite Laundry Service.",
    heroSubtitle: "Free pickup from your Harlem building. Everything washed, dried, and folded. Delivered back within 24 hours. No laundromat. No hassle. Just clean clothes.",
    introParagraph: "Harlem is one of the most historic and energetic neighborhoods in New York City — and its residents deserve a laundry service that keeps up. We Deliver Laundry picks up from your door across Harlem from 110th to 155th Street, washes everything with gentle detergents, and delivers it back the next day perfectly folded. No commitment, no minimums. Starting at $1.95/lb.",
    neighborhoods: ["East Harlem", "Central Harlem", "Hamilton Heights", "Washington Heights", "Sugar Hill"],
    localFAQ_question: "Do you serve all of Harlem from 110th to 155th Street?",
    localFAQ_answer: "Yes — we pick up across all of Harlem. Central Harlem, East Harlem, South Harlem, and Hamilton Heights are all covered. Free pickup, 24-hour turnaround.",
    reviewQuote: "WDL understands that people in Harlem are busy and value their time. Pickup right from my door, back the next day, and the folding is immaculate. A subscriber for life.",
    reviewAuthor: "Tanya B., Harlem",
    zoneCopy: "Pickup across Harlem from 110th to 155th Street. Central Harlem, East Harlem, South Harlem, and Hamilton Heights all covered.",
    finalHeadline: "Harlem Has Better Things to Do.",
    finalSub: "Schedule your first pickup today. Back tomorrow. Perfectly folded.",
    bilingualFlag: false,
    pageType: "nyc",
  },
  "laundry-pickup-hells-kitchen": {
    location: "Hell's Kitchen",
    state: "NYC",
    slug: "laundry-pickup-hells-kitchen",
    metaTitle: "Laundry Pickup & Delivery in Hell's Kitchen, NYC | We Deliver Laundry",
    metaDescription: "Laundry pickup and delivery in Hell's Kitchen, NYC. Wash, dry & fold returned in 24 hours. Starting at $1.95/lb. Free pickup from your building. Book today.",
    h1: "Hell's Kitchen. Hot Neighborhood, Fresh Laundry.",
    heroSubtitle: "Free pickup from your building. Washed, dried, and folded without harsh chemicals. Back at your door in 24 hours — no drama.",
    introParagraph: "Hell's Kitchen is one of Manhattan's most electric neighborhoods — restaurants on every block, theater nearby, always something going on. None of which should involve a laundromat. We Deliver Laundry picks up from your building between 34th and 59th Street, washes everything with care, and delivers it back perfectly folded the next day. Starting at $1.95/lb on the weekly plan.",
    neighborhoods: ["Chelsea", "Midtown West", "Columbus Circle", "Theater District", "Lincoln Square"],
    localFAQ_question: "Do you serve buildings in Hell's Kitchen between 34th and 59th Street?",
    localFAQ_answer: "Yes — we pick up from all Hell's Kitchen addresses west of 8th Avenue. Chelsea, Midtown, and Columbus Circle are also covered. Free pickup, 24-hour turnaround.",
    reviewQuote: "Hell's Kitchen moves fast and so does WDL. Weekly plan, same driver, always on time. My apartment is tiny but at least my laundry is handled.",
    reviewAuthor: "Ryan O., Hell's Kitchen",
    zoneCopy: "Pickup from all Hell's Kitchen addresses between 34th and 59th Street, west of 8th Avenue. Chelsea, Midtown, and Columbus Circle also covered.",
    finalHeadline: "Hell's Kitchen Never Waits.",
    finalSub: "Neither should you. Schedule your first pickup and get your time back.",
    bilingualFlag: false,
    pageType: "nyc",
  },
  "laundry-pickup-lower-east-side": {
    location: "Lower East Side",
    state: "NYC",
    slug: "laundry-pickup-lower-east-side",
    metaTitle: "Laundry Pickup & Delivery on the Lower East Side, NYC | We Deliver Laundry",
    metaDescription: "Laundry pickup and delivery on the Lower East Side, NYC. Wash, dry & fold returned in 24 hours. Starting at $1.95/lb. Free pickup from your building. Book today.",
    h1: "Lower East Side. Always Moving. Laundry Handled.",
    heroSubtitle: "Free pickup from your LES building. Washed, folded, and back at your door in 24 hours. No laundromat. No carrying bags.",
    introParagraph: "The Lower East Side never stops — and neither should you. We Deliver Laundry picks up from your building, washes everything without harsh chemicals, and delivers it back perfectly folded the next day. No more laundromat trips, no more carrying bags down the stairs. Starting at $1.95/lb on the weekly plan.",
    neighborhoods: ["East Village", "Chinatown", "Two Bridges", "Bowery", "NoLiTa"],
    localFAQ_question: "Do you serve apartments on the Lower East Side?",
    localFAQ_answer: "Yes — we pick up from all LES addresses. East Village, Chinatown, Two Bridges, and the Bowery are also covered. Free pickup, 24-hour turnaround.",
    reviewQuote: "The LES is my neighborhood and the laundromat was always the thing I dreaded most. WDL picks up from my building and I genuinely don't think about laundry anymore.",
    reviewAuthor: "Alex T., Lower East Side",
    zoneCopy: "Pickup from all Lower East Side addresses. East Village, Chinatown, Two Bridges, and the Bowery also covered.",
    finalHeadline: "LES Never Stops. Neither Do We.",
    finalSub: "Schedule your first pickup and take laundry off the list for good.",
    bilingualFlag: false,
    pageType: "nyc",
  },
  "laundry-pickup-midtown": {
    location: "Midtown",
    state: "NYC",
    slug: "laundry-pickup-midtown",
    metaTitle: "Laundry Pickup & Delivery in Midtown Manhattan, NYC | We Deliver Laundry",
    metaDescription: "Laundry pickup and delivery in Midtown Manhattan, NYC. Wash, dry & fold returned in 24 hours. Starting at $1.95/lb. Free pickup from your building. Book today.",
    h1: "Midtown Never Slows Down. Neither Does Your Laundry.",
    heroSubtitle: "Free pickup from your Midtown building. Professionally washed, dried, and folded. Back at your door in 24 hours — because your schedule demands it.",
    introParagraph: "Midtown Manhattan is the engine of New York — and if you live here, your time is your most valuable resource. We Deliver Laundry picks up from your building, handles everything professionally, and delivers it back the next day. Weekly plan, consistent pickup times, perfect folding every time. Starting at $1.95/lb.",
    neighborhoods: ["Midtown East", "Midtown West", "Murray Hill", "Flatiron", "Hell's Kitchen"],
    localFAQ_question: "Do you pick up from residential buildings in Midtown Manhattan?",
    localFAQ_answer: "Yes — we serve all Midtown residential buildings. Midtown East, Midtown West, Murray Hill, and Flatiron are also covered. Free pickup, 24-hour turnaround.",
    reviewQuote: "Midtown is the busiest place on earth and I needed a laundry service that could keep up. WDL delivers consistently — same time every week, perfect folds, never late.",
    reviewAuthor: "James R., Midtown",
    zoneCopy: "Pickup from all Midtown Manhattan addresses. Midtown East, Midtown West, Murray Hill, and Flatiron also covered.",
    finalHeadline: "Midtown Moves at One Speed.",
    finalSub: "Fast. Schedule your first pickup and keep your week moving.",
    bilingualFlag: false,
    pageType: "nyc",
  },
  "laundry-pickup-soho": {
    location: "SoHo",
    state: "NYC",
    slug: "laundry-pickup-soho",
    metaTitle: "Laundry Pickup & Delivery in SoHo, NYC | We Deliver Laundry",
    metaDescription: "Laundry pickup and delivery in SoHo, NYC. Wash, dry & fold returned in 24 hours. Starting at $1.95/lb. Free pickup from your building. Book your first pickup today.",
    h1: "SoHo. Style Capital. Laundry-Free Weekends.",
    heroSubtitle: "Free pickup from your SoHo building. Washed without harsh chemicals, folded with precision, back in 24 hours. Your clothes deserve it.",
    introParagraph: "In SoHo, everything is curated — your apartment, your wardrobe, your weekend. Spending Sunday at a laundromat doesn't fit. We Deliver Laundry picks up from your building, washes every item without harsh chemicals, and delivers it back the next day perfectly folded. Your clothes look great. Your Sunday stays yours. Starting at $1.95/lb on the weekly plan.",
    neighborhoods: ["Nolita", "Tribeca", "Greenwich Village", "West Village", "Hudson Square"],
    localFAQ_question: "Do you pick up from loft and apartment buildings in SoHo?",
    localFAQ_answer: "Yes — we serve all SoHo addresses. Nolita, Little Italy, Tribeca, and Greenwich Village are also covered. Free pickup, 24-hour turnaround.",
    reviewQuote: "In SoHo, everything has to look good — and that includes my laundry. WDL treats my clothes with care, uses gentle detergents, and delivers everything perfectly folded.",
    reviewAuthor: "Sophia M., SoHo",
    zoneCopy: "Pickup from all SoHo addresses. Nolita, Little Italy, Tribeca, Greenwich Village, and Hudson Square also covered.",
    finalHeadline: "SoHo Looks Good. So Does Your Laundry.",
    finalSub: "Schedule your first SoHo pickup. Gentle wash, perfect folds, back in 24 hours.",
    bilingualFlag: false,
    pageType: "nyc",
  },
  "laundry-pickup-tribeca": {
    location: "Tribeca",
    state: "NYC",
    slug: "laundry-pickup-tribeca",
    metaTitle: "Laundry Pickup & Delivery in Tribeca, NYC | We Deliver Laundry",
    metaDescription: "Laundry pickup and delivery in Tribeca, NYC. Wash, dry & fold returned in 24 hours. Starting at $1.95/lb. Free pickup from your building. Book your first pickup today.",
    h1: "Tribeca. Premium Block, Premium Laundry Service.",
    heroSubtitle: "Free pickup from your Tribeca building. Washed without harsh chemicals, folded with care, back in 24 hours. Your clothes — and your neighborhood — deserve nothing less.",
    introParagraph: "Tribeca is one of New York's most prestigious neighborhoods — and the standard for every service here is high. We Deliver Laundry picks up from your building, washes everything without harsh chemicals, and delivers it back perfectly folded the next day. Consistent, reliable, and priced fairly for the quality. Starting at $1.95/lb on the weekly plan.",
    neighborhoods: ["SoHo", "Hudson Square", "Financial District", "Battery Park City", "Civic Center"],
    localFAQ_question: "Do you pick up from Tribeca loft and apartment buildings?",
    localFAQ_answer: "Yes — we serve all Tribeca addresses. SoHo, Hudson Square, Financial District, and Civic Center are also covered. Free pickup, 24-hour turnaround.",
    reviewQuote: "Tribeca is premium in every way and WDL matches that standard. Reliable, careful with my clothes, and the pricing is completely fair for the quality. Weekly subscriber.",
    reviewAuthor: "Brandon K., Tribeca",
    zoneCopy: "Pickup from all Tribeca addresses. SoHo, Hudson Square, Financial District, and Civic Center also covered.",
    finalHeadline: "Tribeca Quality. Tribeca Standards.",
    finalSub: "Schedule your first pickup. Washed without harsh chemicals, back in 24 hours, perfectly folded.",
    bilingualFlag: false,
    pageType: "nyc",
  },
  "laundry-pickup-upper-east-side": {
    location: "Upper East Side",
    state: "NYC",
    slug: "laundry-pickup-upper-east-side",
    metaTitle: "Laundry Pickup & Delivery on the Upper East Side, NYC | We Deliver Laundry",
    metaDescription: "Laundry pickup and delivery on the Upper East Side, NYC. Wash, dry & fold returned in 24 hours. Starting at $1.95/lb. Free pickup. Schedule online today.",
    h1: "Upper East Side. The Standard Is High. So Is Our Service.",
    heroSubtitle: "Free pickup from your UES building. Professionally washed without harsh chemicals, perfectly folded, back at your door in 24 hours.",
    introParagraph: "The Upper East Side expects quality in every service — and we deliver it. We Deliver Laundry picks up from your building, washes everything without harsh chemicals, and delivers it back the next day with perfect folds. Consistent pickup times, reliable turnaround, and fair pricing. Starting at $1.95/lb on the weekly plan.",
    neighborhoods: ["Carnegie Hill", "Lenox Hill", "Yorkville", "East Harlem", "Roosevelt Island"],
    localFAQ_question: "Do you serve buildings on the Upper East Side?",
    localFAQ_answer: "Yes — we pick up from all UES addresses. Carnegie Hill, Lenox Hill, Yorkville, and East Harlem are also covered. Free pickup, 24-hour turnaround.",
    reviewQuote: "The Upper East Side expects quality in every service and WDL delivers that completely. Consistent pickup times, immaculate folding, and always on time.",
    reviewAuthor: "Patricia V., Upper East Side",
    zoneCopy: "Pickup from all Upper East Side addresses. Carnegie Hill, Lenox Hill, Yorkville, and the surrounding blocks fully covered.",
    finalHeadline: "UES Quality. Always Delivered.",
    finalSub: "Schedule your first Upper East Side pickup. Washed with care, back in 24 hours.",
    bilingualFlag: false,
    pageType: "nyc",
  },
  "laundry-pickup-upper-west-side": {
    location: "Upper West Side",
    state: "NYC",
    slug: "laundry-pickup-upper-west-side",
    metaTitle: "Laundry Pickup & Delivery on the Upper West Side, NYC | We Deliver Laundry",
    metaDescription: "Laundry pickup and delivery on the Upper West Side, NYC. Wash, dry & fold returned in 24 hours. Starting at $1.95/lb. Free pickup from your building. Book today.",
    h1: "Upper West Side. Parks, Culture, Zero Laundry.",
    heroSubtitle: "Free pickup from your UWS building. Washed without harsh chemicals, perfectly folded, back at your door in 24 hours. More time for the park. Less time in the laundromat.",
    introParagraph: "The Upper West Side has Riverside Park, Central Park, Lincoln Center, and some of the best food in the city. What it doesn't need is laundromat trips. We Deliver Laundry picks up from your building, washes everything with gentle detergents, and delivers it back the next day perfectly folded. The weekly plan keeps your laundry handled automatically. Starting at $1.95/lb.",
    neighborhoods: ["Lincoln Square", "Columbus Circle", "Manhattan Valley", "Morningside Heights"],
    localFAQ_question: "Do you serve apartments on the Upper West Side?",
    localFAQ_answer: "Yes — we pick up from all UWS buildings. Lincoln Square, Columbus Circle, Manhattan Valley, and Morningside Heights are also covered. Free pickup, 24-hour turnaround.",
    reviewQuote: "The Upper West Side is the perfect place to live and WDL is the perfect laundry service for it. Reliable weekly pickup, great folding, and my mornings feel so much lighter.",
    reviewAuthor: "Rachel B., Upper West Side",
    zoneCopy: "Pickup from all Upper West Side addresses. Lincoln Square, Columbus Circle, Manhattan Valley, and Morningside Heights also covered.",
    finalHeadline: "Riverside Park Beats Laundry.",
    finalSub: "Every single time. Schedule your first UWS pickup and spend your weekend the right way.",
    bilingualFlag: false,
    pageType: "nyc",
  },
  "laundry-pickup-washington-heights": {
    location: "Washington Heights",
    state: "NYC",
    slug: "laundry-pickup-washington-heights",
    metaTitle: "Laundry Pickup & Delivery in Washington Heights, NYC | We Deliver Laundry",
    metaDescription: "Laundry pickup and delivery in Washington Heights, NYC. Wash, dry & fold returned in 24 hours. Starting at $1.95/lb. Free pickup. Servicio en español disponible.",
    h1: "Washington Heights. El Trabajo Duro Merece Ropa Limpia.",
    heroSubtitle: "Free pickup from your Washington Heights building. Washed, dried, and folded. Back in 24 hours. Bilingual service available — servicio en español disponible.",
    introParagraph: "Washington Heights es el corazón del Alto Manhattan — una comunidad trabajadora que merece lo mejor. We Deliver Laundry recoge en tu puerta, lava todo con cuidado sin productos agresivos, y te lo devuelve perfectamente doblado al día siguiente. Sin compromiso, sin mínimos, desde $1.95/lb con el plan semanal. Servicio disponible en inglés y español.",
    neighborhoods: ["Inwood", "Hamilton Heights", "Marble Hill", "Central Harlem"],
    localFAQ_question: "¿Recogen ropa en Washington Heights y el Alto Manhattan?",
    localFAQ_answer: "Sí — recogemos en todas las direcciones de Washington Heights. Inwood y Hamilton Heights también están cubiertos. Servicio disponible en español. Recogida gratis, entrega en 24 horas.",
    reviewQuote: "Washington Heights es mi comunidad y WDL lo entiende. Recogen en mi puerta, lo traen de vuelta al día siguiente impecable. El plan semanal vale cada centavo.",
    reviewAuthor: "Carlos R., Washington Heights",
    zoneCopy: "Pickup from all Washington Heights addresses. Inwood, Hamilton Heights, and Marble Hill also covered. Bilingual service available.",
    finalHeadline: "Washington Heights Trabaja Duro.",
    finalSub: "Schedule your first pickup. Bilingual service available. Back in 24 hours, perfectly folded.",
    bilingualFlag: true,
    pageType: "nyc",
  },
  "laundry-pickup-west-village": {
    location: "West Village",
    state: "NYC",
    slug: "laundry-pickup-west-village",
    metaTitle: "Laundry Pickup & Delivery in the West Village, NYC | We Deliver Laundry",
    metaDescription: "Laundry pickup and delivery in the West Village, NYC. Wash, dry & fold returned in 24 hours. Starting at $1.95/lb. Free pickup from your building. Book today.",
    h1: "West Village. Cobblestones & Clean Laundry.",
    heroSubtitle: "Free pickup from your West Village building. Washed without harsh chemicals, perfectly folded, back in 24 hours. The most charming neighborhood in the city — with the best laundry service.",
    introParagraph: "The West Village is one of New York's most beloved neighborhoods — and its residents have better things to do than spend Sunday at a laundromat. We Deliver Laundry picks up from your building, washes everything with gentle detergents, and delivers it back the next morning perfectly folded. Starting at $1.95/lb on the weekly plan.",
    neighborhoods: ["Greenwich Village", "Meatpacking District", "Chelsea", "Hudson Square", "SoHo"],
    localFAQ_question: "Do you pick up from West Village buildings on the cobblestone streets?",
    localFAQ_answer: "Yes — we serve all West Village addresses. Greenwich Village, Meatpacking District, Chelsea, and Hudson Square are also covered. Free pickup, 24-hour turnaround.",
    reviewQuote: "The West Village is my forever home and WDL has become my forever laundry service. Pickup on my block, back the next morning, always perfect. Worth every penny.",
    reviewAuthor: "Nicole A., West Village",
    zoneCopy: "Pickup from all West Village addresses. Greenwich Village, Meatpacking District, Chelsea, and Hudson Square also covered.",
    finalHeadline: "West Village Has Better Plans.",
    finalSub: "Schedule your first pickup and spend your weekend on the cobblestones — not in a laundromat.",
    bilingualFlag: false,
    pageType: "nyc",
  },
  "laundry-pickup-bergen-county-nj": {
    location: "Bergen County",
    state: "NJ",
    slug: "laundry-pickup-bergen-county-nj",
    metaTitle: "Laundry Pickup & Delivery in Bergen County, NJ | We Deliver Laundry",
    metaDescription: "Laundry pickup and delivery in Bergen County, NJ. Wash, dry & fold returned in 24 hours. Starting at $1.95/lb. Free pickup from your door. Schedule online today.",
    h1: "Bergen County, NJ — Laundry Delivered.",
    heroSubtitle: "We pick up from your Bergen County home or apartment — wash, dry and fold everything — and deliver back within 24 hours. Serving all of Bergen County.",
    introParagraph: "Bergen County is home to some of New Jersey's most vibrant communities — from Hackensack and Fort Lee to Ridgewood and Teaneck. We Deliver Laundry brings professional laundry service right to your door. We pick up, handle everything without harsh chemicals, and deliver back the next day perfectly folded. Starting at $1.95/lb on the weekly plan.",
    neighborhoods: ["Hackensack", "Fort Lee", "Paramus", "Teaneck", "Englewood", "Ridgewood", "Fair Lawn", "Clifton"],
    localFAQ_question: "Do you pick up from homes and apartments throughout Bergen County, NJ?",
    localFAQ_answer: "Yes — we serve all of Bergen County including Hackensack, Fort Lee, Paramus, Teaneck, Englewood, Ridgewood, and surrounding towns. Free pickup from your door, 24-hour turnaround.",
    reviewQuote: "I live in Hackensack and WDL has been incredible. They pick up from my door and have it back the next day perfectly folded. The weekly plan saves me hours every week.",
    reviewAuthor: "Jennifer K., Hackensack, Bergen County",
    zoneCopy: "Serving all of Bergen County including Hackensack, Fort Lee, Paramus, Teaneck, Englewood, Ridgewood, Fair Lawn, Clifton, and surrounding towns.",
    finalHeadline: "Bergen County, Laundry Handled.",
    finalSub: "Schedule your first pickup. Free pickup, 24-hour turnaround, $1.95/lb weekly plan.",
    bilingualFlag: false,
    pageType: "nj",
  },
  "laundry-pickup-essex-county-nj": {
    location: "Essex County",
    state: "NJ",
    slug: "laundry-pickup-essex-county-nj",
    metaTitle: "Laundry Pickup & Delivery in Essex County, NJ | We Deliver Laundry",
    metaDescription: "Laundry pickup and delivery in Essex County, NJ including Newark and Montclair. Wash, dry & fold returned in 24 hours. $1.95/lb weekly plan. Free pickup. Book today.",
    h1: "Essex County, NJ — Professional Laundry, Delivered to You.",
    heroSubtitle: "We pick up from your Essex County home or building — wash, dry and fold everything — and deliver back within 24 hours. Serving Newark, Montclair, Maplewood, and beyond.",
    introParagraph: "Essex County spans some of New Jersey's most diverse communities — from urban Newark to suburban Montclair, Maplewood, and South Orange. We Deliver Laundry picks up from your door, washes everything without harsh chemicals, and delivers back the next day perfectly folded. Starting at $1.95/lb on the weekly plan.",
    neighborhoods: ["Newark", "Montclair", "Maplewood", "South Orange", "Bloomfield", "East Orange", "Irvington"],
    localFAQ_question: "Do you serve homes and apartments throughout Essex County, NJ?",
    localFAQ_answer: "Yes — we cover all of Essex County including Newark, Montclair, Maplewood, South Orange, and surrounding towns. Free pickup, 24-hour turnaround.",
    reviewQuote: "I live in Montclair and WDL has been a revelation. Pickup right from my house, back the next day perfectly folded. Best thing I've done for my schedule this year.",
    reviewAuthor: "Diane W., Montclair, Essex County",
    zoneCopy: "Serving all of Essex County including Newark, Montclair, Maplewood, South Orange, Bloomfield, East Orange, Irvington, and surrounding towns.",
    finalHeadline: "Essex County, Zero Laundry Chores.",
    finalSub: "Schedule your first pickup. Free pickup, 24-hour turnaround, starting at $1.95/lb.",
    bilingualFlag: false,
    pageType: "nj",
  },
  "laundry-pickup-hudson-county-nj": {
    location: "Hudson County",
    state: "NJ",
    slug: "laundry-pickup-hudson-county-nj",
    metaTitle: "Laundry Pickup & Delivery in Hudson County, NJ | Jersey City & Hoboken | We Deliver Laundry",
    metaDescription: "Laundry pickup and delivery in Hudson County, NJ. Serving Jersey City, Hoboken, and more. Wash, dry & fold returned in 24 hours. $1.95/lb. Free pickup. Book today.",
    h1: "Hudson County, NJ — NYC Views, NYC-Quality Laundry.",
    heroSubtitle: "We pick up from your Hudson County home or apartment — wash, dry and fold everything — and deliver back within 24 hours. Jersey City, Hoboken, and beyond.",
    introParagraph: "Hudson County is right across the river from Manhattan — and its residents expect Manhattan-quality services. We Deliver Laundry picks up from your door in Jersey City, Hoboken, Bayonne, Weehawken, and throughout Hudson County, washes everything without harsh chemicals, and delivers it back the next day perfectly folded. Starting at $1.95/lb on the weekly plan.",
    neighborhoods: ["Jersey City", "Hoboken", "Bayonne", "Weehawken", "Union City", "West New York"],
    localFAQ_question: "Do you pick up from apartments in Jersey City and Hoboken?",
    localFAQ_answer: "Yes — we serve all of Hudson County including Jersey City, Hoboken, Bayonne, Weehawken, Union City, and West New York. Free pickup from your door, 24-hour turnaround.",
    reviewQuote: "Living in Jersey City with the NYC skyline view, I wanted NYC-quality services. WDL delivers exactly that — pickup from my door in Jersey City, back the next day, perfect.",
    reviewAuthor: "Marco S., Jersey City, Hudson County",
    zoneCopy: "Serving all of Hudson County including Jersey City, Hoboken, Bayonne, Weehawken, Union City, West New York, and surrounding towns.",
    finalHeadline: "Hudson County, Best Views and Best Laundry.",
    finalSub: "Schedule your first pickup. Free pickup, 24-hour turnaround, $1.95/lb weekly plan.",
    bilingualFlag: false,
    pageType: "nj",
  },
  "laundry-pickup-morris-county-nj": {
    location: "Morris County",
    state: "NJ",
    slug: "laundry-pickup-morris-county-nj",
    metaTitle: "Laundry Pickup & Delivery in Morris County, NJ | We Deliver Laundry",
    metaDescription: "Laundry pickup and delivery in Morris County, NJ including Morristown and Parsippany. Wash, dry & fold returned in 24 hours. $1.95/lb weekly plan. Free pickup. Book today.",
    h1: "Morris County, NJ — Suburban Living, Zero Laundry Days.",
    heroSubtitle: "We pick up from your Morris County home — wash, dry and fold everything — and deliver back within 24 hours. Serving Morristown, Parsippany, and all surrounding towns.",
    introParagraph: "Morris County offers the best of New Jersey suburban living — and busy families and professionals here deserve a laundry service that comes to them. We Deliver Laundry picks up from your door throughout Morris County, washes everything without harsh chemicals, and delivers back the next day perfectly folded. Starting at $1.95/lb on the weekly plan.",
    neighborhoods: ["Morristown", "Parsippany", "Rockaway", "Dover", "Florham Park", "Madison"],
    localFAQ_question: "Do you pick up from homes in Morristown and throughout Morris County?",
    localFAQ_answer: "Yes — we serve all of Morris County including Morristown, Parsippany, Rockaway, Dover, and surrounding towns. Free pickup from your door, 24-hour turnaround.",
    reviewQuote: "Morris County is suburban and quiet and WDL fits perfectly. They come right to my door in Morristown and have everything back the next day immaculate. Perfect service.",
    reviewAuthor: "Robert L., Morristown, Morris County",
    zoneCopy: "Serving all of Morris County including Morristown, Parsippany, Rockaway, Dover, Florham Park, Madison, and surrounding towns.",
    finalHeadline: "Morris County Deserves This.",
    finalSub: "Schedule your first pickup. Free pickup, 24-hour turnaround, starting at $1.95/lb.",
    bilingualFlag: false,
    pageType: "nj",
  },
  "laundry-pickup-passaic-county-nj": {
    location: "Passaic County",
    state: "NJ",
    slug: "laundry-pickup-passaic-county-nj",
    metaTitle: "Laundry Pickup & Delivery in Passaic County, NJ | We Deliver Laundry",
    metaDescription: "Laundry pickup and delivery in Passaic County, NJ including Paterson and Clifton. Wash, dry & fold in 24 hours. $1.95/lb weekly plan. Free pickup. Bilingual service.",
    h1: "Passaic County, NJ — Hardworking Community, Clean Clothes.",
    heroSubtitle: "We pick up from your Passaic County home — wash, dry and fold everything — and deliver back within 24 hours. Bilingual service available — servicio en español disponible.",
    introParagraph: "Passaic County es una comunidad trabajadora — Paterson, Clifton, Passaic, Wayne y muchas ciudades más. We Deliver Laundry recoge en tu puerta, lava todo con cuidado sin productos agresivos, y te lo devuelve perfectamente doblado al día siguiente. Servicio disponible en inglés y español. Desde $1.95/lb con el plan semanal.",
    neighborhoods: ["Paterson", "Clifton", "Passaic", "Wayne", "Totowa", "Little Falls"],
    localFAQ_question: "¿Recogen ropa en Paterson, Clifton y toda el área de Passaic County?",
    localFAQ_answer: "Sí — cubrimos todo el condado de Passaic incluyendo Paterson, Clifton, Passaic, Wayne y ciudades cercanas. Servicio disponible en español. Recogida gratis, entrega en 24 horas.",
    reviewQuote: "Vivimos en Passaic y WDL ha sido increíble para nuestra familia. Recogen en nuestra puerta cada semana y todo vuelve perfectamente doblado al día siguiente.",
    reviewAuthor: "Maria G., Passaic, Passaic County",
    zoneCopy: "Serving all of Passaic County including Paterson, Clifton, Passaic, Wayne, Totowa, Little Falls, and surrounding towns. Bilingual service available.",
    finalHeadline: "Passaic County, Ropa Limpia en 24 Horas.",
    finalSub: "Schedule your first pickup. Bilingual service available. Free pickup, next-day delivery.",
    bilingualFlag: true,
    pageType: "nj",
  },
  "laundry-pickup-union-county-nj": {
    location: "Union County",
    state: "NJ",
    slug: "laundry-pickup-union-county-nj",
    metaTitle: "Laundry Pickup & Delivery in Union County, NJ | We Deliver Laundry",
    metaDescription: "Laundry pickup and delivery in Union County, NJ including Elizabeth and Westfield. Wash, dry & fold returned in 24 hours. $1.95/lb weekly plan. Free pickup. Book today.",
    h1: "Union County, NJ — Convenient Location, Even More Convenient Laundry.",
    heroSubtitle: "We pick up from your Union County home — wash, dry and fold everything — and deliver back within 24 hours. Serving Elizabeth, Summit, Westfield, and beyond.",
    introParagraph: "Union County connects New Jersey's suburban communities to the greater New York metro area — and its residents expect services that match that pace. We Deliver Laundry picks up from your door throughout Union County, washes everything without harsh chemicals, and delivers back the next day perfectly folded. Starting at $1.95/lb on the weekly plan.",
    neighborhoods: ["Elizabeth", "Summit", "Westfield", "Plainfield", "Union Township", "Linden", "Rahway"],
    localFAQ_question: "Do you serve homes in Elizabeth, Westfield, and throughout Union County?",
    localFAQ_answer: "Yes — we cover all of Union County including Elizabeth, Summit, Westfield, Plainfield, and surrounding towns. Free pickup from your door, 24-hour turnaround.",
    reviewQuote: "I live in Westfield and WDL has been perfect for our busy family. Pickup Wednesday, back Thursday, four people's laundry completely handled. The weekly plan is a lifesaver.",
    reviewAuthor: "Susan H., Westfield, Union County",
    zoneCopy: "Serving all of Union County including Elizabeth, Summit, Westfield, Plainfield, Union Township, Linden, Rahway, and surrounding towns.",
    finalHeadline: "Union County, Laundry Handled.",
    finalSub: "Schedule your first pickup. Free pickup, 24-hour turnaround, starting at $1.95/lb.",
    bilingualFlag: false,
    pageType: "nj",
  },
};

export function getLocationPage(slug: string): LocationPage | null {
  return locationPages[slug] ?? null;
}

export function getAllLocationSlugs(): { slug: string }[] {
  return Object.keys(locationPages).map((slug) => ({ slug }));
}
